language: python
cache:
  - apt
  - pip
python:
  - "2.7"
services:
  - postgresql
  - elasticsearch
addons:
  postgresql: "9.4"
  apt:
    packages:
      - python-software-properties
      - libtesseract-dev
      - wkhtmltopdf
      - poppler-utils
      - libreoffice
env:
  - ALEPH_TEST_SETTINGS=$TRAVIS_BUILD_DIR/test_settings.py
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr-eng readpst
install:
  - gem install sass
  - pip install -r requirements.txt
  - pip install -e .
  - pip install psycopg2 coveralls
  - npm install -g bower uglifyjs
  - bower install
before_script:
  - psql -c 'create database aleph_test;' -U postgres
  - cp $TRAVIS_BUILD_DIR/test_settings.py.tmpl $TRAVIS_BUILD_DIR/test_settings.py
  - nosetests --version
  - psql --version
script:
  - nosetests --with-coverage --cover-package=aleph
after_success:
  - coveralls
