
postgres:
  image: postgres:9.4
  volumes:
    - "/srv/data/postgres:/var/lib/postgresql/data"
    - "/srv/logs/postgres:/var/log"
  environment:
    POSTGRES_USER:     aleph
    POSTGRES_PASSWORD: aleph
    POSTGRES_DATABASE: aleph
  ports:
    - "127.0.0.1:5433:5432"

elasticsearch:
  image: elasticsearch:1.7.2
  volumes:
    - "/srv/data/elasticsearch:/usr/share/elasticsearch/data"
    - "/srv/logs/elasticsearch:/var/log"
  ports:
    - "127.0.0.1:9201:9200"
  environment:
    ES_HEAP_SIZE: 4g

rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - "/srv/data/rabbitmq/:/var/lib/rabbitmq"
    expose:
      - "5673"
      - "15672"

worker:
    build: .
    command: celery -A aleph.queue worker -c 10 -l INFO --logfile=/var/log/celery.log
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    volumes:
      - "/srv/data:/srv/data/"
      - "/srv/logs/worker:/var/log"
    environment:
      C_FORCE_ROOT: true
      ALEPH_ELASTICSEARCH_URI: http://aleph_elasticsearch:9200/
      ALEPH_DATABASE_URI: postgresql://aleph:aleph@localhost/aleph
      ALEPH_BROKER_URI: amqp://guest:guest@aleph_rabbitmq:5672//
      ALEPH_ARCHIVE_TYPE: file
      ALEPH_ARCHIVE_PATH: /srv/data/aleph
    env_file:
      - aleph.env

web:
    build: .
    command: gunicorn -w 5 -b 0.0.0.0:8000 --log-level info --log-file - aleph.manage:app
    ports:
      - "13376:8000"
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    volumes:
      - "/srv/data/:/srv/data/"
      - "/srv/data/live/aleph-logs/worker:/var/log"
    environment:
      ALEPH_ELASTICSEARCH_URI: http://aleph_elasticsearch:9200/
      ALEPH_DATABASE_URI: postgresql://aleph:aleph@localhost/aleph
      ALEPH_BROKER_URI: amqp://guest:guest@aleph_rabbitmq:5672//
      ALEPH_ARCHIVE_TYPE: file
      ALEPH_ARCHIVE_PATH: /srv/data/aleph
    env_file:
      - aleph.env
